.TH XScreenSaver 1 "" "X Version 11"
.SH NAME
coral \- simulates coral growth, albeit somewhat slowly.
.SH SYNOPSIS
.B coral
[\-\-display \fIhost:display.screen\fP]
[\-\-visual \fIvisual\fP]
[\-\-window]
[\-\-root]
[\-\-window\-id \fInumber\fP]
[\-\-delay2 \fInumber\fP]
[\-\-delay \fInumber\fP]
[\-\-density \fInumber\fP]
[\-\-seeds \fInumber\fP]
[\-\-fps]
.SH DESCRIPTION
Simulates coral growth, albeit somewhat slowly.
.SH OPTIONS
.TP 8
.B \-\-visual \fIvisual\fP
Specify which visual to use.  Legal values are the name of a visual class,
or the id number (decimal or hex) of a specific visual.
.TP 8
.B \-\-window
Draw on a newly-created window.  This is the default.
.TP 8
.B \-\-root
Draw on the root window.
.TP 8
.B \-\-window\-id \fInumber\fP
Draw on the specified window.
.TP 8
.B \-\-delay2 \fInumber\fP
Per-frame delay, in microseconds.  Default: 1000 (0.001 seconds.).
.TP 8
.B \-\-delay \fInumber\fP
Duration.  1 - 60.  Default: 5.
.TP 8
.B \-\-density \fInumber\fP
Density.  1 - 90.  Default: 25.
.TP 8
.B \-\-seeds \fInumber\fP
Seeds.	1 - 100.  Default: 20.
.TP 8
.B \-\-fps
Display the current frame rate and CPU load.
.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY
to get the default host and display number.
.TP 8
.B XENVIRONMENT
to get the name of a resource file that overrides the global resources
stored in the RESOURCE_MANAGER property.
.TP 8
.B XSCREENSAVER_WINDOW
The window ID to use with \fI\-\-root\fP.
.SH SEE ALSO
.BR X (1),
.BR xscreensaver (1)
.SH COPYRIGHT
Copyright \(co 2002 by Frederick Roeber.  Permission to use, copy, modify, 
distribute, and sell this software and its documentation for any purpose is 
hereby granted without fee, provided that the above copyright notice appear 
in all copies and that both that copyright notice and this permission notice
appear in supporting documentation.  No representations are made about the 
suitability of this software for any purpose.  It is provided "as is" without
express or implied warranty.
.SH AUTHOR
Frederick Roeber.
