.TH XScreenSaver 1 "" "X Version 11"
.SH NAME
fireworkx - pyrotechnics simulation eye-candy.
.SH SYNOPSIS
.B fireworkx
[\-display \fIhost:display.screen\fP]
[\-visual \fIvisual\fP]
[\-window]
[\-root]
[\-verbose]
[\-fade]
[\-nolight]
[\-shoot]
[\-delay \fInumber\fP]
[\-maxlife \fInumber\fP]
.SH DESCRIPTION
Simulates fireworks (pyrotechnics); explodes better on faster machines.
.SH OPTIONS
.TP 8
.B \-visual \fIvisual\fP
Specify which visual to use.  Legal values are the name of a visual class,
or the id number (decimal or hex) of a specific visual.
.TP 8
.B \-window
Draw on a newly-created window.  This is the default.
.TP 8
.B \-root
Draw on the root window.
.TP 8
.B \-nolight
Turns off light effect; runs faster.
.TP 8
.B \-fade
Cuts the extra blur; looks more realistic.
.TP 8
.B \-shoot
Shows shooting of the shells.
.TP 8
.B \-delay \fInumber\fP
Delay between frames. In microseconds. 
.TP 8
.B \-maxlife \fInumber\fP
Maximum decay period for an explosion. (Default: 1200)
.TP 8
.B \-verbose
Listen what the program have to say, via console.
.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY
to get the default host and display number.
.TP 8
.B XENVIRONMENT
to get the name of a resource file that overrides the global resources
stored in the RESOURCE_MANAGER property.
.SH SEE ALSO
.BR X (1),
.BR xscreensaver (1)
.SH COPYRIGHT
Copyright \(co 1999-2004 by Rony B Chandran.  Permission to use, copy, modify, 
distribute, and sell this software and its documentation for any purpose is 
hereby granted without fee, provided that the above copyright notice appear 
in all copies and that both that copyright notice and this permission notice
appear in supporting documentation.  No representations are made about the 
suitability of this software for any purpose.  It is provided "as is" without
express or implied warranty.
.SH AUTHOR
Written by Rony B Chandran <ronybc@asia.com>

Added support for different display color modes
by Jean-Pierre Demailly <Jean-Pierre.Demailly@ujf-grenoble.fr>

.SH URL 
http://www.ronybc.8k.com

