.TH XScreenSaver 1 "" "X Version 11"
.SH NAME
flow - strange attractors.
.SH SYNOPSIS
.B flow
[\-display \fIhost:display.screen\fP]
[\-visual \fIvisual\fP]
[\-window]
[\-root]
[\-count \fInumber\fP]
[\-cycles \fInumber\fP]
[\-delay \fInumber\fP]
[\-ncolors \fInumber\fP]
[\-rotate \fIbool\fP]
[\-ride \fIbool\fP]
[\-zoom \fIbool\fP]
[\-box \fIbool\fP]
[\-freeze \fIbool\fP]
[\-allow2d \fIbool\fP]
[\-slow \fIbool\fP]
.SH DESCRIPTION
Another series of strange attractors: a flowing series of points, making
strange rotational shapes.
.SH OPTIONS
.TP 8
.B \-visual \fIvisual\fP
Specify which visual to use.  Legal values are the name of a visual class,
or the id number (decimal or hex) of a specific visual.
.TP 8
.B \-window
Draw on a newly-created window.  This is the default.
.TP 8
.B \-root
Draw on the root window.
.TP 8
.B \-count \fInumber\fP
Number of pixels.  Default: 500.
.TP 8
.B \-cycles \fInumber\fP
Timeout before changing objects.  0 - 800000.  Default: 3000.
.TP 8
.B \-delay \fInumber\fP
Per-frame delay, in microseconds.  Default: 1000 (0.001 seconds.).
.TP 8
.B \-ncolors \fInumber\fP
Number of Colors.  Default: 200.
.TP 8
.B \-rotate
Rotate Around Attractor.
.TP 8
.B \-ride
Ride a Trained Bee.
.TP 8
.B \-zoom
Zoom In and Out.
.TP 8
.B \-box
Show Bounding Box.
.TP 8
.B \-freeze
Freeze Some Bees.
.TP 8
.B \-allow2d
Allow 2D Attractors.
.TP 8
.B \-slow
Slow Bees with Antifreeze.
.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY
to get the default host and display number.
.TP 8
.B XENVIRONMENT
to get the name of a resource file that overrides the global resources
stored in the RESOURCE_MANAGER property.
.SH SEE ALSO
.BR X (1),
.BR xscreensaver (1)
.SH COPYRIGHT

Copyright \(co 2002 by Tim Auckland and Jeff Butterworth.  Permission
to use, copy, modify, distribute, and sell this software and its
documentation for any purpose is hereby granted without fee, provided
that the above copyright notice appear in all copies and that both that
copyright notice and this permission notice appear in supporting
documentation.  No representations are made about the suitability of
this software for any purpose.  It is provided "as is" without express
or implied warranty.

.SH AUTHOR
Tim Auckland based on code by Jeff Butterworth.
