.TH XScreenSaver 1 "" "X Version 11"
.SH NAME
ifs - draws spinning, colliding iterated-function-system images
.SH SYNOPSIS
.B ifs
[\-display \fIhost:display.screen\fP]
[\-visual \fIvisual\fP]
[\-window]
[\-root]
[\-delay \fInumber\fP]
[\-detail \fInumber\fP]
[\-mode \fImode\fP]
[\-colors \fInumber\fP]
[\-functions \fInumber\fP]
.SH DESCRIPTION
The \fIifs\fP program draws spinning, colliding iterated-function-system images.
.SH OPTIONS
.TP 8
.B \-visual \fIvisual\fP
Specify which visual to use.  Legal values are the name of a visual class,
or the id number (decimal or hex) of a specific visual.
.TP 8
.B \-window
Draw on a newly-created window.  This is the default.
.TP 8
.B \-root
Draw on the root window.
.TP 8
.B \-delay \fInumber\fP
Per-frame delay, in microseconds.  Default: 10000
.TP 8
.B \-mode \fImode\fP
Colouring mode. 0 = blend, 1 = per-function, 2 = single colour.  Default: 0
.TP 8
.B \-colors \fInumber\fP
Number of colours to use. Default: 200
.TP 8
.B \-detail \fInumber\fP
Number of times to iterate each function. Default: 9
.TP 8
.B \-functions \fInumber\fP
Number of functions to be iterated. Default: 3
.TP 8
.B \-ncolors \fInumber\fP
Number of colors.  Default: 20.
.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY
to get the default host and display number.
.TP 8
.B XENVIRONMENT
to get the name of a resource file that overrides the global resources
stored in the RESOURCE_MANAGER property.
.SH SEE ALSO
.BR X (1),
.BR xscreensaver (1),
.BR ifs (1)
.SH COPYRIGHT
Copyright \(co Chris Le Sueur (thefishface@gmail.com) February 2005

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE X CONSORTIUM BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
.SH AUTHOR
Chris Le Sueur
