$ def sys sys$library:
$ CC/DEFINE=VMS FADE.C
$ CC/DEFINE=VMS GRABSCREEN.C
$ CC/DEFINE=VMS HSV.C
$ CC/DEFINE=VMS RESOURCES.C
$ CC/DEFINE=VMS SPLINE.C
$ CC/DEFINE=VMS USLEEP.C
$ CC/DEFINE=VMS XROGER.C
$ CC/DEFINE=VMS STRINGS.C
$ CC/DEFINE=VMS YARANDOM.C
$ CC/DEFINE=VMS UNIX_TIMES.C
$ CC/DEFINE=VMS VISUAL.C
$! lib/cre utils.olb
$! lib utils.olb *.obj
$! delete/noconf *.obj;
