.TH XScreenSaver 1 "4-Jun-2019 (5.43)" "X Version 11"
.SH NAME
xscreensaver-systemd - lock the screen when the machine suspends.
.SH SYNOPSIS
.B xscreensaver-systemd
.SH DESCRIPTION
The \fIxscreensaver\-systemd\fP program is a helper program to
integrate xscreensaver with 
.BR systemd (1).
When run from \fI~/.xsession\fP or equivalent, this will:
.TP 3
\fB1:
Lock the screen before the system goes to sleep
(using \fIxscreensaver-command -suspend\fP).
.TP 3
\fB2:
Ensure the XScreenSaver password dialog is shown after the system
is resumed (using \fIxscreensaver-command -deactivate\fP).
.RS 0

This is implemented using inhibitor locks;
.BR sd-bus (3)
is used for DBUS communication.
.SH BUGS
Uses libsystemd.
.SH SEE ALSO
.BR X (1),
.BR xscreensaver (1),
.BR xscreensaver\-demo (1),
.BR xscreensaver\-command (1),
.BR systemd (1),
.BR sd-bus (3)
.SH COPYRIGHT
Copyright \(co 2019 by Martin Lucina.  
Permission to use, copy, modify, and/or distribute this software
for any purpose with or without fee is hereby granted, provided
that the above copyright notice and this permission notice appear
in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.SH AUTHOR
Martin Lucina <martin@lucina.net>, 4-Jun-2019
