.TH XScreenSaver 1 "06-Jan-2021 (6.00)" "X Version 11"
.SH NAME
xscreensaver - extensible screen saver and screen locking framework
.SH SYNOPSIS
.B xscreensaver-auth
[\-\-display \fIhost:display.screen\fP]
.SH DESCRIPTION
The
.BR xscreensaver (1)
daemon launches this program to prompt the user for their password.
Do not run this program directly.
.SH SEE ALSO
.BR xscreensaver (1),
.BR xscreensaver\-settings (1),
.BR xscreensaver\-gfx (MANSUFFIX),
.BR xscreensaver\-systemd (MANSUFFIX).
.SH COPYRIGHT
Copyright \(co 2021 by Jamie Zawinski.
Permission to use, copy, modify, distribute, and sell this software
and its documentation for any purpose is hereby granted without fee,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation.  No representations are made about the
suitability of this software for any purpose.  It is provided "as is"
without express or implied warranty.
.SH AUTHOR
Jamie Zawinski <jwz@jwz.org>
