/* Generated file, do not edit.
   Created: Sat Apr 27 19:53:47 2019 by build-fntable.pl 1.7.
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

extern NSDictionary *make_function_table_dict(void);

extern struct xscreensaver_function_table
 abstractile_xscreensaver_function_table,
 anemone_xscreensaver_function_table,
 anemotaxis_xscreensaver_function_table,
 antinspect_xscreensaver_function_table,
 antmaze_xscreensaver_function_table,
 antspotlight_xscreensaver_function_table,
 apollonian_xscreensaver_function_table,
 apple2_xscreensaver_function_table,
 atlantis_xscreensaver_function_table,
 attraction_xscreensaver_function_table,
 atunnel_xscreensaver_function_table,
 barcode_xscreensaver_function_table,
 binaryring_xscreensaver_function_table,
 blaster_xscreensaver_function_table,
 blinkbox_xscreensaver_function_table,
 blitspin_xscreensaver_function_table,
 blocktube_xscreensaver_function_table,
 boing_xscreensaver_function_table,
 bouboule_xscreensaver_function_table,
 bouncingcow_xscreensaver_function_table,
 boxed_xscreensaver_function_table,
 boxfit_xscreensaver_function_table,
 braid_xscreensaver_function_table,
 bsod_xscreensaver_function_table,
 bubble3d_xscreensaver_function_table,
 bumps_xscreensaver_function_table,
 cage_xscreensaver_function_table,
 carousel_xscreensaver_function_table,
 ccurve_xscreensaver_function_table,
 celtic_xscreensaver_function_table,
 circuit_xscreensaver_function_table,
 cityflow_xscreensaver_function_table,
 cloudlife_xscreensaver_function_table,
 companioncube_xscreensaver_function_table,
 compass_xscreensaver_function_table,
 coral_xscreensaver_function_table,
 crackberg_xscreensaver_function_table,
 crumbler_xscreensaver_function_table,
 crystal_xscreensaver_function_table,
 cube21_xscreensaver_function_table,
 cubenetic_xscreensaver_function_table,
 cubestack_xscreensaver_function_table,
 cubestorm_xscreensaver_function_table,
 cubetwist_xscreensaver_function_table,
 cubicgrid_xscreensaver_function_table,
 cwaves_xscreensaver_function_table,
 cynosure_xscreensaver_function_table,
 dangerball_xscreensaver_function_table,
 decayscreen_xscreensaver_function_table,
 deco_xscreensaver_function_table,
 deepstars_xscreensaver_function_table,
 deluxe_xscreensaver_function_table,
 demon_xscreensaver_function_table,
 discoball_xscreensaver_function_table,
 discrete_xscreensaver_function_table,
 distort_xscreensaver_function_table,
 dnalogo_xscreensaver_function_table,
 drift_xscreensaver_function_table,
 dymaxionmap_xscreensaver_function_table,
 endgame_xscreensaver_function_table,
 energystream_xscreensaver_function_table,
 engine_xscreensaver_function_table,
 epicycle_xscreensaver_function_table,
 eruption_xscreensaver_function_table,
 esper_xscreensaver_function_table,
 euler2d_xscreensaver_function_table,
 fadeplot_xscreensaver_function_table,
 fiberlamp_xscreensaver_function_table,
 filmleader_xscreensaver_function_table,
 fireworkx_xscreensaver_function_table,
 flame_xscreensaver_function_table,
 flipflop_xscreensaver_function_table,
 flipscreen3d_xscreensaver_function_table,
 fliptext_xscreensaver_function_table,
 flow_xscreensaver_function_table,
 fluidballs_xscreensaver_function_table,
 flyingtoasters_xscreensaver_function_table,
 fontglide_xscreensaver_function_table,
 fuzzyflakes_xscreensaver_function_table,
 galaxy_xscreensaver_function_table,
 gears_xscreensaver_function_table,
 geodesic_xscreensaver_function_table,
 geodesicgears_xscreensaver_function_table,
 gflux_xscreensaver_function_table,
 glblur_xscreensaver_function_table,
 glcells_xscreensaver_function_table,
 gleidescope_xscreensaver_function_table,
 glhanoi_xscreensaver_function_table,
 glknots_xscreensaver_function_table,
 glmatrix_xscreensaver_function_table,
 glplanet_xscreensaver_function_table,
 glschool_xscreensaver_function_table,
 glslideshow_xscreensaver_function_table,
 glsnake_xscreensaver_function_table,
 gltext_xscreensaver_function_table,
 goop_xscreensaver_function_table,
 grav_xscreensaver_function_table,
 gravitywell_xscreensaver_function_table,
 greynetic_xscreensaver_function_table,
 halftone_xscreensaver_function_table,
 halo_xscreensaver_function_table,
 handsy_xscreensaver_function_table,
 helix_xscreensaver_function_table,
 hexadrop_xscreensaver_function_table,
 hexstrut_xscreensaver_function_table,
 hilbert_xscreensaver_function_table,
 hopalong_xscreensaver_function_table,
 hydrostat_xscreensaver_function_table,
 hypertorus_xscreensaver_function_table,
 hypnowheel_xscreensaver_function_table,
 ifs_xscreensaver_function_table,
 imsmap_xscreensaver_function_table,
 interaggregate_xscreensaver_function_table,
 interference_xscreensaver_function_table,
 intermomentary_xscreensaver_function_table,
 jigglypuff_xscreensaver_function_table,
 jigsaw_xscreensaver_function_table,
 juggler3d_xscreensaver_function_table,
 julia_xscreensaver_function_table,
 kaleidescope_xscreensaver_function_table,
 kaleidocycle_xscreensaver_function_table,
 klein_xscreensaver_function_table,
 kumppa_xscreensaver_function_table,
 lament_xscreensaver_function_table,
 lavalite_xscreensaver_function_table,
 loop_xscreensaver_function_table,
 m6502_xscreensaver_function_table,
 maze_xscreensaver_function_table,
 maze3d_xscreensaver_function_table,
 memscroller_xscreensaver_function_table,
 menger_xscreensaver_function_table,
 metaballs_xscreensaver_function_table,
 mirrorblob_xscreensaver_function_table,
 moebius_xscreensaver_function_table,
 moebiusgears_xscreensaver_function_table,
 moire_xscreensaver_function_table,
 moire2_xscreensaver_function_table,
 molecule_xscreensaver_function_table,
 morph3d_xscreensaver_function_table,
 mountain_xscreensaver_function_table,
 munch_xscreensaver_function_table,
 nerverot_xscreensaver_function_table,
 noof_xscreensaver_function_table,
 noseguy_xscreensaver_function_table,
 pacman_xscreensaver_function_table,
 pedal_xscreensaver_function_table,
 peepers_xscreensaver_function_table,
 penetrate_xscreensaver_function_table,
 penrose_xscreensaver_function_table,
 petri_xscreensaver_function_table,
 phosphor_xscreensaver_function_table,
 photopile_xscreensaver_function_table,
 piecewise_xscreensaver_function_table,
 pinion_xscreensaver_function_table,
 pipes_xscreensaver_function_table,
 polyhedra_xscreensaver_function_table,
 polyominoes_xscreensaver_function_table,
 polytopes_xscreensaver_function_table,
 pong_xscreensaver_function_table,
 popsquares_xscreensaver_function_table,
 projectiveplane_xscreensaver_function_table,
 providence_xscreensaver_function_table,
 pulsar_xscreensaver_function_table,
 pyro_xscreensaver_function_table,
 qix_xscreensaver_function_table,
 quasicrystal_xscreensaver_function_table,
 queens_xscreensaver_function_table,
 raverhoop_xscreensaver_function_table,
 razzledazzle_xscreensaver_function_table,
 rdbomb_xscreensaver_function_table,
 ripples_xscreensaver_function_table,
 rocks_xscreensaver_function_table,
 romanboy_xscreensaver_function_table,
 rorschach_xscreensaver_function_table,
 rotzoomer_xscreensaver_function_table,
 rubik_xscreensaver_function_table,
 rubikblocks_xscreensaver_function_table,
 sballs_xscreensaver_function_table,
 shadebobs_xscreensaver_function_table,
 sierpinski_xscreensaver_function_table,
 sierpinski3d_xscreensaver_function_table,
 skytentacles_xscreensaver_function_table,
 slidescreen_xscreensaver_function_table,
 slip_xscreensaver_function_table,
 sonar_xscreensaver_function_table,
 speedmine_xscreensaver_function_table,
 spheremonics_xscreensaver_function_table,
 splitflap_xscreensaver_function_table,
 splodesic_xscreensaver_function_table,
 spotlight_xscreensaver_function_table,
 sproingies_xscreensaver_function_table,
 squiral_xscreensaver_function_table,
 stairs_xscreensaver_function_table,
 starfish_xscreensaver_function_table,
 starwars_xscreensaver_function_table,
 stonerview_xscreensaver_function_table,
 strange_xscreensaver_function_table,
 substrate_xscreensaver_function_table,
 superquadrics_xscreensaver_function_table,
 surfaces_xscreensaver_function_table,
 swirl_xscreensaver_function_table,
 tangram_xscreensaver_function_table,
 tessellimage_xscreensaver_function_table,
 thornbird_xscreensaver_function_table,
 timetunnel_xscreensaver_function_table,
 topblock_xscreensaver_function_table,
 triangle_xscreensaver_function_table,
 tronbit_xscreensaver_function_table,
 truchet_xscreensaver_function_table,
 twang_xscreensaver_function_table,
 unicrud_xscreensaver_function_table,
 unknownpleasures_xscreensaver_function_table,
 vermiculate_xscreensaver_function_table,
 vfeedback_xscreensaver_function_table,
 vigilance_xscreensaver_function_table,
 voronoi_xscreensaver_function_table,
 wander_xscreensaver_function_table,
 whirlwindwarp_xscreensaver_function_table,
 winduprobot_xscreensaver_function_table,
 wormhole_xscreensaver_function_table,
 xanalogtv_xscreensaver_function_table,
 xflame_xscreensaver_function_table,
 xjack_xscreensaver_function_table,
 xlyap_xscreensaver_function_table,
 xmatrix_xscreensaver_function_table,
 xrayswarm_xscreensaver_function_table,
 xspirograph_xscreensaver_function_table,
 zoom_xscreensaver_function_table,
 testx11_xscreensaver_function_table;

NSDictionary *make_function_table_dict(void)
{
  return
    [NSDictionary dictionaryWithObjectsAndKeys:

#if defined(APPLE2_ONLY)
 	[NSValue valueWithPointer:&apple2_xscreensaver_function_table], @"apple2",
#elif defined(PHOSPHOR_ONLY)
 	[NSValue valueWithPointer:&phosphor_xscreensaver_function_table], @"phosphor",
#elif defined(TESTX11_ONLY)
 	[NSValue valueWithPointer:&testx11_xscreensaver_function_table], @"testx11",
#else
	[NSValue valueWithPointer:&abstractile_xscreensaver_function_table], @"abstractile",
	[NSValue valueWithPointer:&anemone_xscreensaver_function_table], @"anemone",
	[NSValue valueWithPointer:&anemotaxis_xscreensaver_function_table], @"anemotaxis",
	[NSValue valueWithPointer:&antinspect_xscreensaver_function_table], @"antinspect",
	[NSValue valueWithPointer:&antmaze_xscreensaver_function_table], @"antmaze",
	[NSValue valueWithPointer:&antspotlight_xscreensaver_function_table], @"antspotlight",
	[NSValue valueWithPointer:&apollonian_xscreensaver_function_table], @"apollonian",
	[NSValue valueWithPointer:&apple2_xscreensaver_function_table], @"apple2",
	[NSValue valueWithPointer:&atlantis_xscreensaver_function_table], @"atlantis",
	[NSValue valueWithPointer:&attraction_xscreensaver_function_table], @"attraction",
	[NSValue valueWithPointer:&atunnel_xscreensaver_function_table], @"atunnel",
	[NSValue valueWithPointer:&barcode_xscreensaver_function_table], @"barcode",
	[NSValue valueWithPointer:&binaryring_xscreensaver_function_table], @"binaryring",
	[NSValue valueWithPointer:&blaster_xscreensaver_function_table], @"blaster",
	[NSValue valueWithPointer:&blinkbox_xscreensaver_function_table], @"blinkbox",
	[NSValue valueWithPointer:&blitspin_xscreensaver_function_table], @"blitspin",
	[NSValue valueWithPointer:&blocktube_xscreensaver_function_table], @"blocktube",
	[NSValue valueWithPointer:&boing_xscreensaver_function_table], @"boing",
	[NSValue valueWithPointer:&bouboule_xscreensaver_function_table], @"bouboule",
	[NSValue valueWithPointer:&bouncingcow_xscreensaver_function_table], @"bouncingcow",
	[NSValue valueWithPointer:&boxed_xscreensaver_function_table], @"boxed",
	[NSValue valueWithPointer:&boxfit_xscreensaver_function_table], @"boxfit",
	[NSValue valueWithPointer:&braid_xscreensaver_function_table], @"braid",
	[NSValue valueWithPointer:&bsod_xscreensaver_function_table], @"bsod",
	[NSValue valueWithPointer:&bubble3d_xscreensaver_function_table], @"bubble3d",
	[NSValue valueWithPointer:&bumps_xscreensaver_function_table], @"bumps",
	[NSValue valueWithPointer:&cage_xscreensaver_function_table], @"cage",
	[NSValue valueWithPointer:&carousel_xscreensaver_function_table], @"carousel",
	[NSValue valueWithPointer:&ccurve_xscreensaver_function_table], @"ccurve",
	[NSValue valueWithPointer:&celtic_xscreensaver_function_table], @"celtic",
	[NSValue valueWithPointer:&circuit_xscreensaver_function_table], @"circuit",
	[NSValue valueWithPointer:&cityflow_xscreensaver_function_table], @"cityflow",
	[NSValue valueWithPointer:&cloudlife_xscreensaver_function_table], @"cloudlife",
	[NSValue valueWithPointer:&companioncube_xscreensaver_function_table], @"companioncube",
	[NSValue valueWithPointer:&compass_xscreensaver_function_table], @"compass",
	[NSValue valueWithPointer:&coral_xscreensaver_function_table], @"coral",
	[NSValue valueWithPointer:&crackberg_xscreensaver_function_table], @"crackberg",
	[NSValue valueWithPointer:&crumbler_xscreensaver_function_table], @"crumbler",
	[NSValue valueWithPointer:&crystal_xscreensaver_function_table], @"crystal",
	[NSValue valueWithPointer:&cube21_xscreensaver_function_table], @"cube21",
	[NSValue valueWithPointer:&cubenetic_xscreensaver_function_table], @"cubenetic",
	[NSValue valueWithPointer:&cubestack_xscreensaver_function_table], @"cubestack",
	[NSValue valueWithPointer:&cubestorm_xscreensaver_function_table], @"cubestorm",
	[NSValue valueWithPointer:&cubetwist_xscreensaver_function_table], @"cubetwist",
	[NSValue valueWithPointer:&cubicgrid_xscreensaver_function_table], @"cubicgrid",
	[NSValue valueWithPointer:&cwaves_xscreensaver_function_table], @"cwaves",
	[NSValue valueWithPointer:&cynosure_xscreensaver_function_table], @"cynosure",
	[NSValue valueWithPointer:&dangerball_xscreensaver_function_table], @"dangerball",
	[NSValue valueWithPointer:&decayscreen_xscreensaver_function_table], @"decayscreen",
	[NSValue valueWithPointer:&deco_xscreensaver_function_table], @"deco",
	[NSValue valueWithPointer:&deepstars_xscreensaver_function_table], @"deepstars",
	[NSValue valueWithPointer:&deluxe_xscreensaver_function_table], @"deluxe",
	[NSValue valueWithPointer:&demon_xscreensaver_function_table], @"demon",
	[NSValue valueWithPointer:&discoball_xscreensaver_function_table], @"discoball",
	[NSValue valueWithPointer:&discrete_xscreensaver_function_table], @"discrete",
	[NSValue valueWithPointer:&distort_xscreensaver_function_table], @"distort",
	[NSValue valueWithPointer:&dnalogo_xscreensaver_function_table], @"dnalogo",
	[NSValue valueWithPointer:&drift_xscreensaver_function_table], @"drift",
	[NSValue valueWithPointer:&dymaxionmap_xscreensaver_function_table], @"dymaxionmap",
	[NSValue valueWithPointer:&endgame_xscreensaver_function_table], @"endgame",
	[NSValue valueWithPointer:&energystream_xscreensaver_function_table], @"energystream",
	[NSValue valueWithPointer:&engine_xscreensaver_function_table], @"engine",
	[NSValue valueWithPointer:&epicycle_xscreensaver_function_table], @"epicycle",
	[NSValue valueWithPointer:&eruption_xscreensaver_function_table], @"eruption",
	[NSValue valueWithPointer:&esper_xscreensaver_function_table], @"esper",
	[NSValue valueWithPointer:&euler2d_xscreensaver_function_table], @"euler2d",
	[NSValue valueWithPointer:&fadeplot_xscreensaver_function_table], @"fadeplot",
	[NSValue valueWithPointer:&fiberlamp_xscreensaver_function_table], @"fiberlamp",
	[NSValue valueWithPointer:&filmleader_xscreensaver_function_table], @"filmleader",
	[NSValue valueWithPointer:&fireworkx_xscreensaver_function_table], @"fireworkx",
	[NSValue valueWithPointer:&flame_xscreensaver_function_table], @"flame",
	[NSValue valueWithPointer:&flipflop_xscreensaver_function_table], @"flipflop",
	[NSValue valueWithPointer:&flipscreen3d_xscreensaver_function_table], @"flipscreen3d",
	[NSValue valueWithPointer:&fliptext_xscreensaver_function_table], @"fliptext",
	[NSValue valueWithPointer:&flow_xscreensaver_function_table], @"flow",
	[NSValue valueWithPointer:&fluidballs_xscreensaver_function_table], @"fluidballs",
	[NSValue valueWithPointer:&flyingtoasters_xscreensaver_function_table], @"flyingtoasters",
	[NSValue valueWithPointer:&fontglide_xscreensaver_function_table], @"fontglide",
	[NSValue valueWithPointer:&fuzzyflakes_xscreensaver_function_table], @"fuzzyflakes",
	[NSValue valueWithPointer:&galaxy_xscreensaver_function_table], @"galaxy",
	[NSValue valueWithPointer:&gears_xscreensaver_function_table], @"gears",
	[NSValue valueWithPointer:&geodesic_xscreensaver_function_table], @"geodesic",
	[NSValue valueWithPointer:&geodesicgears_xscreensaver_function_table], @"geodesicgears",
	[NSValue valueWithPointer:&gflux_xscreensaver_function_table], @"gflux",
	[NSValue valueWithPointer:&glblur_xscreensaver_function_table], @"glblur",
	[NSValue valueWithPointer:&glcells_xscreensaver_function_table], @"glcells",
	[NSValue valueWithPointer:&gleidescope_xscreensaver_function_table], @"gleidescope",
	[NSValue valueWithPointer:&glhanoi_xscreensaver_function_table], @"glhanoi",
	[NSValue valueWithPointer:&glknots_xscreensaver_function_table], @"glknots",
	[NSValue valueWithPointer:&glmatrix_xscreensaver_function_table], @"glmatrix",
	[NSValue valueWithPointer:&glplanet_xscreensaver_function_table], @"glplanet",
	[NSValue valueWithPointer:&glschool_xscreensaver_function_table], @"glschool",
	[NSValue valueWithPointer:&glslideshow_xscreensaver_function_table], @"glslideshow",
	[NSValue valueWithPointer:&glsnake_xscreensaver_function_table], @"glsnake",
	[NSValue valueWithPointer:&gltext_xscreensaver_function_table], @"gltext",
	[NSValue valueWithPointer:&goop_xscreensaver_function_table], @"goop",
	[NSValue valueWithPointer:&grav_xscreensaver_function_table], @"grav",
	[NSValue valueWithPointer:&gravitywell_xscreensaver_function_table], @"gravitywell",
	[NSValue valueWithPointer:&greynetic_xscreensaver_function_table], @"greynetic",
	[NSValue valueWithPointer:&halftone_xscreensaver_function_table], @"halftone",
	[NSValue valueWithPointer:&halo_xscreensaver_function_table], @"halo",
	[NSValue valueWithPointer:&handsy_xscreensaver_function_table], @"handsy",
	[NSValue valueWithPointer:&helix_xscreensaver_function_table], @"helix",
	[NSValue valueWithPointer:&hexadrop_xscreensaver_function_table], @"hexadrop",
	[NSValue valueWithPointer:&hexstrut_xscreensaver_function_table], @"hexstrut",
	[NSValue valueWithPointer:&hilbert_xscreensaver_function_table], @"hilbert",
	[NSValue valueWithPointer:&hopalong_xscreensaver_function_table], @"hopalong",
	[NSValue valueWithPointer:&hydrostat_xscreensaver_function_table], @"hydrostat",
	[NSValue valueWithPointer:&hypertorus_xscreensaver_function_table], @"hypertorus",
	[NSValue valueWithPointer:&hypnowheel_xscreensaver_function_table], @"hypnowheel",
	[NSValue valueWithPointer:&ifs_xscreensaver_function_table], @"ifs",
	[NSValue valueWithPointer:&imsmap_xscreensaver_function_table], @"imsmap",
	[NSValue valueWithPointer:&interaggregate_xscreensaver_function_table], @"interaggregate",
	[NSValue valueWithPointer:&interference_xscreensaver_function_table], @"interference",
	[NSValue valueWithPointer:&intermomentary_xscreensaver_function_table], @"intermomentary",
	[NSValue valueWithPointer:&jigglypuff_xscreensaver_function_table], @"jigglypuff",
	[NSValue valueWithPointer:&jigsaw_xscreensaver_function_table], @"jigsaw",
	[NSValue valueWithPointer:&juggler3d_xscreensaver_function_table], @"juggler3d",
	[NSValue valueWithPointer:&julia_xscreensaver_function_table], @"julia",
	[NSValue valueWithPointer:&kaleidescope_xscreensaver_function_table], @"kaleidescope",
	[NSValue valueWithPointer:&kaleidocycle_xscreensaver_function_table], @"kaleidocycle",
	[NSValue valueWithPointer:&klein_xscreensaver_function_table], @"klein",
	[NSValue valueWithPointer:&kumppa_xscreensaver_function_table], @"kumppa",
	[NSValue valueWithPointer:&lament_xscreensaver_function_table], @"lament",
	[NSValue valueWithPointer:&lavalite_xscreensaver_function_table], @"lavalite",
	[NSValue valueWithPointer:&loop_xscreensaver_function_table], @"loop",
	[NSValue valueWithPointer:&m6502_xscreensaver_function_table], @"m6502",
	[NSValue valueWithPointer:&maze_xscreensaver_function_table], @"maze",
	[NSValue valueWithPointer:&maze3d_xscreensaver_function_table], @"maze3d",
	[NSValue valueWithPointer:&memscroller_xscreensaver_function_table], @"memscroller",
	[NSValue valueWithPointer:&menger_xscreensaver_function_table], @"menger",
	[NSValue valueWithPointer:&metaballs_xscreensaver_function_table], @"metaballs",
	[NSValue valueWithPointer:&mirrorblob_xscreensaver_function_table], @"mirrorblob",
	[NSValue valueWithPointer:&moebius_xscreensaver_function_table], @"moebius",
	[NSValue valueWithPointer:&moebiusgears_xscreensaver_function_table], @"moebiusgears",
	[NSValue valueWithPointer:&moire_xscreensaver_function_table], @"moire",
	[NSValue valueWithPointer:&moire2_xscreensaver_function_table], @"moire2",
	[NSValue valueWithPointer:&molecule_xscreensaver_function_table], @"molecule",
	[NSValue valueWithPointer:&morph3d_xscreensaver_function_table], @"morph3d",
	[NSValue valueWithPointer:&mountain_xscreensaver_function_table], @"mountain",
	[NSValue valueWithPointer:&munch_xscreensaver_function_table], @"munch",
	[NSValue valueWithPointer:&nerverot_xscreensaver_function_table], @"nerverot",
	[NSValue valueWithPointer:&noof_xscreensaver_function_table], @"noof",
	[NSValue valueWithPointer:&noseguy_xscreensaver_function_table], @"noseguy",
	[NSValue valueWithPointer:&pacman_xscreensaver_function_table], @"pacman",
	[NSValue valueWithPointer:&pedal_xscreensaver_function_table], @"pedal",
	[NSValue valueWithPointer:&peepers_xscreensaver_function_table], @"peepers",
	[NSValue valueWithPointer:&penetrate_xscreensaver_function_table], @"penetrate",
	[NSValue valueWithPointer:&penrose_xscreensaver_function_table], @"penrose",
	[NSValue valueWithPointer:&petri_xscreensaver_function_table], @"petri",
	[NSValue valueWithPointer:&phosphor_xscreensaver_function_table], @"phosphor",
	[NSValue valueWithPointer:&photopile_xscreensaver_function_table], @"photopile",
	[NSValue valueWithPointer:&piecewise_xscreensaver_function_table], @"piecewise",
	[NSValue valueWithPointer:&pinion_xscreensaver_function_table], @"pinion",
	[NSValue valueWithPointer:&pipes_xscreensaver_function_table], @"pipes",
	[NSValue valueWithPointer:&polyhedra_xscreensaver_function_table], @"polyhedra",
	[NSValue valueWithPointer:&polyominoes_xscreensaver_function_table], @"polyominoes",
	[NSValue valueWithPointer:&polytopes_xscreensaver_function_table], @"polytopes",
	[NSValue valueWithPointer:&pong_xscreensaver_function_table], @"pong",
	[NSValue valueWithPointer:&popsquares_xscreensaver_function_table], @"popsquares",
	[NSValue valueWithPointer:&projectiveplane_xscreensaver_function_table], @"projectiveplane",
	[NSValue valueWithPointer:&providence_xscreensaver_function_table], @"providence",
	[NSValue valueWithPointer:&pulsar_xscreensaver_function_table], @"pulsar",
	[NSValue valueWithPointer:&pyro_xscreensaver_function_table], @"pyro",
	[NSValue valueWithPointer:&qix_xscreensaver_function_table], @"qix",
	[NSValue valueWithPointer:&quasicrystal_xscreensaver_function_table], @"quasicrystal",
	[NSValue valueWithPointer:&queens_xscreensaver_function_table], @"queens",
	[NSValue valueWithPointer:&raverhoop_xscreensaver_function_table], @"raverhoop",
	[NSValue valueWithPointer:&razzledazzle_xscreensaver_function_table], @"razzledazzle",
	[NSValue valueWithPointer:&rdbomb_xscreensaver_function_table], @"rdbomb",
	[NSValue valueWithPointer:&ripples_xscreensaver_function_table], @"ripples",
	[NSValue valueWithPointer:&rocks_xscreensaver_function_table], @"rocks",
	[NSValue valueWithPointer:&romanboy_xscreensaver_function_table], @"romanboy",
	[NSValue valueWithPointer:&rorschach_xscreensaver_function_table], @"rorschach",
	[NSValue valueWithPointer:&rotzoomer_xscreensaver_function_table], @"rotzoomer",
	[NSValue valueWithPointer:&rubik_xscreensaver_function_table], @"rubik",
	[NSValue valueWithPointer:&rubikblocks_xscreensaver_function_table], @"rubikblocks",
	[NSValue valueWithPointer:&sballs_xscreensaver_function_table], @"sballs",
	[NSValue valueWithPointer:&shadebobs_xscreensaver_function_table], @"shadebobs",
	[NSValue valueWithPointer:&sierpinski_xscreensaver_function_table], @"sierpinski",
	[NSValue valueWithPointer:&sierpinski3d_xscreensaver_function_table], @"sierpinski3d",
	[NSValue valueWithPointer:&skytentacles_xscreensaver_function_table], @"skytentacles",
	[NSValue valueWithPointer:&slidescreen_xscreensaver_function_table], @"slidescreen",
	[NSValue valueWithPointer:&slip_xscreensaver_function_table], @"slip",
	[NSValue valueWithPointer:&sonar_xscreensaver_function_table], @"sonar",
	[NSValue valueWithPointer:&speedmine_xscreensaver_function_table], @"speedmine",
	[NSValue valueWithPointer:&spheremonics_xscreensaver_function_table], @"spheremonics",
	[NSValue valueWithPointer:&splitflap_xscreensaver_function_table], @"splitflap",
	[NSValue valueWithPointer:&splodesic_xscreensaver_function_table], @"splodesic",
	[NSValue valueWithPointer:&spotlight_xscreensaver_function_table], @"spotlight",
	[NSValue valueWithPointer:&sproingies_xscreensaver_function_table], @"sproingies",
	[NSValue valueWithPointer:&squiral_xscreensaver_function_table], @"squiral",
	[NSValue valueWithPointer:&stairs_xscreensaver_function_table], @"stairs",
	[NSValue valueWithPointer:&starfish_xscreensaver_function_table], @"starfish",
	[NSValue valueWithPointer:&starwars_xscreensaver_function_table], @"starwars",
	[NSValue valueWithPointer:&stonerview_xscreensaver_function_table], @"stonerview",
	[NSValue valueWithPointer:&strange_xscreensaver_function_table], @"strange",
	[NSValue valueWithPointer:&substrate_xscreensaver_function_table], @"substrate",
	[NSValue valueWithPointer:&superquadrics_xscreensaver_function_table], @"superquadrics",
	[NSValue valueWithPointer:&surfaces_xscreensaver_function_table], @"surfaces",
	[NSValue valueWithPointer:&swirl_xscreensaver_function_table], @"swirl",
	[NSValue valueWithPointer:&tangram_xscreensaver_function_table], @"tangram",
	[NSValue valueWithPointer:&tessellimage_xscreensaver_function_table], @"tessellimage",
	[NSValue valueWithPointer:&thornbird_xscreensaver_function_table], @"thornbird",
	[NSValue valueWithPointer:&timetunnel_xscreensaver_function_table], @"timetunnel",
	[NSValue valueWithPointer:&topblock_xscreensaver_function_table], @"topblock",
	[NSValue valueWithPointer:&triangle_xscreensaver_function_table], @"triangle",
	[NSValue valueWithPointer:&tronbit_xscreensaver_function_table], @"tronbit",
	[NSValue valueWithPointer:&truchet_xscreensaver_function_table], @"truchet",
	[NSValue valueWithPointer:&twang_xscreensaver_function_table], @"twang",
	[NSValue valueWithPointer:&unicrud_xscreensaver_function_table], @"unicrud",
	[NSValue valueWithPointer:&unknownpleasures_xscreensaver_function_table], @"unknownpleasures",
	[NSValue valueWithPointer:&vermiculate_xscreensaver_function_table], @"vermiculate",
	[NSValue valueWithPointer:&vfeedback_xscreensaver_function_table], @"vfeedback",
	[NSValue valueWithPointer:&vigilance_xscreensaver_function_table], @"vigilance",
	[NSValue valueWithPointer:&voronoi_xscreensaver_function_table], @"voronoi",
	[NSValue valueWithPointer:&wander_xscreensaver_function_table], @"wander",
	[NSValue valueWithPointer:&whirlwindwarp_xscreensaver_function_table], @"whirlwindwarp",
	[NSValue valueWithPointer:&winduprobot_xscreensaver_function_table], @"winduprobot",
	[NSValue valueWithPointer:&wormhole_xscreensaver_function_table], @"wormhole",
	[NSValue valueWithPointer:&xanalogtv_xscreensaver_function_table], @"xanalogtv",
	[NSValue valueWithPointer:&xflame_xscreensaver_function_table], @"xflame",
	[NSValue valueWithPointer:&xjack_xscreensaver_function_table], @"xjack",
	[NSValue valueWithPointer:&xlyap_xscreensaver_function_table], @"xlyap",
	[NSValue valueWithPointer:&xmatrix_xscreensaver_function_table], @"xmatrix",
	[NSValue valueWithPointer:&xrayswarm_xscreensaver_function_table], @"xrayswarm",
	[NSValue valueWithPointer:&xspirograph_xscreensaver_function_table], @"xspirograph",
	[NSValue valueWithPointer:&zoom_xscreensaver_function_table], @"zoom",
#endif
	nil];
}

