/* Generated file, do not edit.
   Created: Thu Dec 24 07:44:49 2020 by build-fntable.pl 1.10.
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

extern NSDictionary *make_function_table_dict(void);

extern struct xscreensaver_function_table
 abstractile_xscreensaver_function_table,
 anemone_xscreensaver_function_table,
 anemotaxis_xscreensaver_function_table,
 antinspect_xscreensaver_function_table,
 antmaze_xscreensaver_function_table,
 antspotlight_xscreensaver_function_table,
 apollonian_xscreensaver_function_table,
 apple2_xscreensaver_function_table,
 atlantis_xscreensaver_function_table,
 attraction_xscreensaver_function_table,
 atunnel_xscreensaver_function_table,
 barcode_xscreensaver_function_table,
 beats_xscreensaver_function_table,
 binaryring_xscreensaver_function_table,
 blaster_xscreensaver_function_table,
 blinkbox_xscreensaver_function_table,
 blitspin_xscreensaver_function_table,
 blocktube_xscreensaver_function_table,
 boing_xscreensaver_function_table,
 bouboule_xscreensaver_function_table,
 bouncingcow_xscreensaver_function_table,
 boxed_xscreensaver_function_table,
 boxfit_xscreensaver_function_table,
 braid_xscreensaver_function_table,
 bsod_xscreensaver_function_table,
 bubble3d_xscreensaver_function_table,
 bumps_xscreensaver_function_table,
 cage_xscreensaver_function_table,
 carousel_xscreensaver_function_table,
 ccurve_xscreensaver_function_table,
 celtic_xscreensaver_function_table,
 circuit_xscreensaver_function_table,
 cityflow_xscreensaver_function_table,
 cloudlife_xscreensaver_function_table,
 co____9_xscreensaver_function_table,
 companioncube_xscreensaver_function_table,
 compass_xscreensaver_function_table,
 coral_xscreensaver_function_table,
 crackberg_xscreensaver_function_table,
 crumbler_xscreensaver_function_table,
 crystal_xscreensaver_function_table,
 cube21_xscreensaver_function_table,
 cubenetic_xscreensaver_function_table,
 cubestack_xscreensaver_function_table,
 cubestorm_xscreensaver_function_table,
 cubetwist_xscreensaver_function_table,
 cubicgrid_xscreensaver_function_table,
 cwaves_xscreensaver_function_table,
 cynosure_xscreensaver_function_table,
 dangerball_xscreensaver_function_table,
 decayscreen_xscreensaver_function_table,
 deco_xscreensaver_function_table,
 deepstars_xscreensaver_function_table,
 deluxe_xscreensaver_function_table,
 demon_xscreensaver_function_table,
 discoball_xscreensaver_function_table,
 discrete_xscreensaver_function_table,
 distort_xscreensaver_function_table,
 dnalogo_xscreensaver_function_table,
 drift_xscreensaver_function_table,
 dymaxionmap_xscreensaver_function_table,
 endgame_xscreensaver_function_table,
 energystream_xscreensaver_function_table,
 engine_xscreensaver_function_table,
 epicycle_xscreensaver_function_table,
 eruption_xscreensaver_function_table,
 esper_xscreensaver_function_table,
 etruscanvenus_xscreensaver_function_table,
 euler2d_xscreensaver_function_table,
 fadeplot_xscreensaver_function_table,
 fiberlamp_xscreensaver_function_table,
 filmleader_xscreensaver_function_table,
 fireworkx_xscreensaver_function_table,
 flame_xscreensaver_function_table,
 flipflop_xscreensaver_function_table,
 flipscreen3d_xscreensaver_function_table,
 fliptext_xscreensaver_function_table,
 flow_xscreensaver_function_table,
 fluidballs_xscreensaver_function_table,
 flyingtoasters_xscreensaver_function_table,
 fontglide_xscreensaver_function_table,
 fuzzyflakes_xscreensaver_function_table,
 galaxy_xscreensaver_function_table,
 gears_xscreensaver_function_table,
 geodesic_xscreensaver_function_table,
 geodesicgears_xscreensaver_function_table,
 gflux_xscreensaver_function_table,
 gibson_xscreensaver_function_table,
 glblur_xscreensaver_function_table,
 glcells_xscreensaver_function_table,
 gleidescope_xscreensaver_function_table,
 glhanoi_xscreensaver_function_table,
 glknots_xscreensaver_function_table,
 glmatrix_xscreensaver_function_table,
 glplanet_xscreensaver_function_table,
 glschool_xscreensaver_function_table,
 glslideshow_xscreensaver_function_table,
 glsnake_xscreensaver_function_table,
 gltext_xscreensaver_function_table,
 goop_xscreensaver_function_table,
 grav_xscreensaver_function_table,
 gravitywell_xscreensaver_function_table,
 greynetic_xscreensaver_function_table,
 halftone_xscreensaver_function_table,
 halo_xscreensaver_function_table,
 handsy_xscreensaver_function_table,
 headroom_xscreensaver_function_table,
 helix_xscreensaver_function_table,
 hexadrop_xscreensaver_function_table,
 hexstrut_xscreensaver_function_table,
 hilbert_xscreensaver_function_table,
 hopalong_xscreensaver_function_table,
 hydrostat_xscreensaver_function_table,
 hypertorus_xscreensaver_function_table,
 hypnowheel_xscreensaver_function_table,
 ifs_xscreensaver_function_table,
 imsmap_xscreensaver_function_table,
 interaggregate_xscreensaver_function_table,
 interference_xscreensaver_function_table,
 intermomentary_xscreensaver_function_table,
 jigglypuff_xscreensaver_function_table,
 jigsaw_xscreensaver_function_table,
 juggler3d_xscreensaver_function_table,
 julia_xscreensaver_function_table,
 kaleidescope_xscreensaver_function_table,
 kaleidocycle_xscreensaver_function_table,
 klein_xscreensaver_function_table,
 kumppa_xscreensaver_function_table,
 lament_xscreensaver_function_table,
 lavalite_xscreensaver_function_table,
 loop_xscreensaver_function_table,
 m6502_xscreensaver_function_table,
 maze_xscreensaver_function_table,
 maze3d_xscreensaver_function_table,
 memscroller_xscreensaver_function_table,
 menger_xscreensaver_function_table,
 metaballs_xscreensaver_function_table,
 mirrorblob_xscreensaver_function_table,
 moebius_xscreensaver_function_table,
 moebiusgears_xscreensaver_function_table,
 moire_xscreensaver_function_table,
 moire2_xscreensaver_function_table,
 molecule_xscreensaver_function_table,
 morph3d_xscreensaver_function_table,
 mountain_xscreensaver_function_table,
 munch_xscreensaver_function_table,
 nerverot_xscreensaver_function_table,
 noof_xscreensaver_function_table,
 noseguy_xscreensaver_function_table,
 pacman_xscreensaver_function_table,
 pedal_xscreensaver_function_table,
 peepers_xscreensaver_function_table,
 penetrate_xscreensaver_function_table,
 penrose_xscreensaver_function_table,
 petri_xscreensaver_function_table,
 phosphor_xscreensaver_function_table,
 photopile_xscreensaver_function_table,
 piecewise_xscreensaver_function_table,
 pinion_xscreensaver_function_table,
 pipes_xscreensaver_function_table,
 polyhedra_xscreensaver_function_table,
 polyominoes_xscreensaver_function_table,
 polytopes_xscreensaver_function_table,
 pong_xscreensaver_function_table,
 popsquares_xscreensaver_function_table,
 projectiveplane_xscreensaver_function_table,
 providence_xscreensaver_function_table,
 pulsar_xscreensaver_function_table,
 pyro_xscreensaver_function_table,
 qix_xscreensaver_function_table,
 quasicrystal_xscreensaver_function_table,
 queens_xscreensaver_function_table,
 raverhoop_xscreensaver_function_table,
 razzledazzle_xscreensaver_function_table,
 rdbomb_xscreensaver_function_table,
 ripples_xscreensaver_function_table,
 rocks_xscreensaver_function_table,
 romanboy_xscreensaver_function_table,
 rorschach_xscreensaver_function_table,
 rotzoomer_xscreensaver_function_table,
 rubik_xscreensaver_function_table,
 rubikblocks_xscreensaver_function_table,
 sballs_xscreensaver_function_table,
 scooter_xscreensaver_function_table,
 shadebobs_xscreensaver_function_table,
 sierpinski_xscreensaver_function_table,
 sierpinski3d_xscreensaver_function_table,
 skytentacles_xscreensaver_function_table,
 slidescreen_xscreensaver_function_table,
 slip_xscreensaver_function_table,
 sonar_xscreensaver_function_table,
 speedmine_xscreensaver_function_table,
 sphereeversion_xscreensaver_function_table,
 spheremonics_xscreensaver_function_table,
 splitflap_xscreensaver_function_table,
 splodesic_xscreensaver_function_table,
 spotlight_xscreensaver_function_table,
 sproingies_xscreensaver_function_table,
 squiral_xscreensaver_function_table,
 stairs_xscreensaver_function_table,
 starfish_xscreensaver_function_table,
 starwars_xscreensaver_function_table,
 stonerview_xscreensaver_function_table,
 strange_xscreensaver_function_table,
 substrate_xscreensaver_function_table,
 superquadrics_xscreensaver_function_table,
 surfaces_xscreensaver_function_table,
 swirl_xscreensaver_function_table,
 tangram_xscreensaver_function_table,
 tessellimage_xscreensaver_function_table,
 thornbird_xscreensaver_function_table,
 timetunnel_xscreensaver_function_table,
 topblock_xscreensaver_function_table,
 triangle_xscreensaver_function_table,
 tronbit_xscreensaver_function_table,
 truchet_xscreensaver_function_table,
 twang_xscreensaver_function_table,
 unicrud_xscreensaver_function_table,
 unknownpleasures_xscreensaver_function_table,
 vermiculate_xscreensaver_function_table,
 vfeedback_xscreensaver_function_table,
 vigilance_xscreensaver_function_table,
 voronoi_xscreensaver_function_table,
 wander_xscreensaver_function_table,
 whirlwindwarp_xscreensaver_function_table,
 winduprobot_xscreensaver_function_table,
 wormhole_xscreensaver_function_table,
 xanalogtv_xscreensaver_function_table,
 xflame_xscreensaver_function_table,
 xjack_xscreensaver_function_table,
 xlyap_xscreensaver_function_table,
 xmatrix_xscreensaver_function_table,
 xrayswarm_xscreensaver_function_table,
 xspirograph_xscreensaver_function_table,
 zoom_xscreensaver_function_table,
 testx11_xscreensaver_function_table;

NSDictionary *make_function_table_dict(void) {
  return @{
#if defined(APPLE2_ONLY)
	@"Apple ][":	[NSValue valueWithPointer:&apple2_xscreensaver_function_table],
#elif defined(PHOSPHOR_ONLY)
	@"Phosphor":	[NSValue valueWithPointer:&phosphor_xscreensaver_function_table],
#elif defined(TESTX11_ONLY)
	@"Test X11":	[NSValue valueWithPointer:&testx11_xscreensaver_function_table],
#else
	@"Abstractile":	[NSValue valueWithPointer:&abstractile_xscreensaver_function_table],
	@"Anemone":	[NSValue valueWithPointer:&anemone_xscreensaver_function_table],
	@"Anemotaxis":	[NSValue valueWithPointer:&anemotaxis_xscreensaver_function_table],
	@"Ant Inspect":	[NSValue valueWithPointer:&antinspect_xscreensaver_function_table],
	@"Ant Maze":	[NSValue valueWithPointer:&antmaze_xscreensaver_function_table],
	@"Ant Spotlight":	[NSValue valueWithPointer:&antspotlight_xscreensaver_function_table],
	@"Apollonian":	[NSValue valueWithPointer:&apollonian_xscreensaver_function_table],
	@"Apple ][":	[NSValue valueWithPointer:&apple2_xscreensaver_function_table],
	@"Atlantis":	[NSValue valueWithPointer:&atlantis_xscreensaver_function_table],
	@"Attraction":	[NSValue valueWithPointer:&attraction_xscreensaver_function_table],
	@"Atunnel":	[NSValue valueWithPointer:&atunnel_xscreensaver_function_table],
	@"Barcode":	[NSValue valueWithPointer:&barcode_xscreensaver_function_table],
	@"Beats":	[NSValue valueWithPointer:&beats_xscreensaver_function_table],
	@"Binary Ring":	[NSValue valueWithPointer:&binaryring_xscreensaver_function_table],
	@"Blaster":	[NSValue valueWithPointer:&blaster_xscreensaver_function_table],
	@"Blink Box":	[NSValue valueWithPointer:&blinkbox_xscreensaver_function_table],
	@"Blit Spin":	[NSValue valueWithPointer:&blitspin_xscreensaver_function_table],
	@"Block Tube":	[NSValue valueWithPointer:&blocktube_xscreensaver_function_table],
	@"Boing":	[NSValue valueWithPointer:&boing_xscreensaver_function_table],
	@"Bouboule":	[NSValue valueWithPointer:&bouboule_xscreensaver_function_table],
	@"Bouncing Cow":	[NSValue valueWithPointer:&bouncingcow_xscreensaver_function_table],
	@"Boxed":	[NSValue valueWithPointer:&boxed_xscreensaver_function_table],
	@"Box Fit":	[NSValue valueWithPointer:&boxfit_xscreensaver_function_table],
	@"Braid":	[NSValue valueWithPointer:&braid_xscreensaver_function_table],
	@"BSOD":	[NSValue valueWithPointer:&bsod_xscreensaver_function_table],
	@"Bubble 3D":	[NSValue valueWithPointer:&bubble3d_xscreensaver_function_table],
	@"Bumps":	[NSValue valueWithPointer:&bumps_xscreensaver_function_table],
	@"Cage":	[NSValue valueWithPointer:&cage_xscreensaver_function_table],
	@"Carousel":	[NSValue valueWithPointer:&carousel_xscreensaver_function_table],
	@"C Curve":	[NSValue valueWithPointer:&ccurve_xscreensaver_function_table],
	@"Celtic":	[NSValue valueWithPointer:&celtic_xscreensaver_function_table],
	@"Circuit":	[NSValue valueWithPointer:&circuit_xscreensaver_function_table],
	@"City Flow":	[NSValue valueWithPointer:&cityflow_xscreensaver_function_table],
	@"Cloud Life":	[NSValue valueWithPointer:&cloudlife_xscreensaver_function_table],
	@"Co____9":	[NSValue valueWithPointer:&co____9_xscreensaver_function_table],
	@"Companion Cube":	[NSValue valueWithPointer:&companioncube_xscreensaver_function_table],
	@"Compass":	[NSValue valueWithPointer:&compass_xscreensaver_function_table],
	@"Coral":	[NSValue valueWithPointer:&coral_xscreensaver_function_table],
	@"Crackberg":	[NSValue valueWithPointer:&crackberg_xscreensaver_function_table],
	@"Crumbler":	[NSValue valueWithPointer:&crumbler_xscreensaver_function_table],
	@"Crystal":	[NSValue valueWithPointer:&crystal_xscreensaver_function_table],
	@"Cube 21":	[NSValue valueWithPointer:&cube21_xscreensaver_function_table],
	@"Cubenetic":	[NSValue valueWithPointer:&cubenetic_xscreensaver_function_table],
	@"Cube Stack":	[NSValue valueWithPointer:&cubestack_xscreensaver_function_table],
	@"Cube Storm":	[NSValue valueWithPointer:&cubestorm_xscreensaver_function_table],
	@"Cube Twist":	[NSValue valueWithPointer:&cubetwist_xscreensaver_function_table],
	@"Cubic Grid":	[NSValue valueWithPointer:&cubicgrid_xscreensaver_function_table],
	@"C Waves":	[NSValue valueWithPointer:&cwaves_xscreensaver_function_table],
	@"Cynosure":	[NSValue valueWithPointer:&cynosure_xscreensaver_function_table],
	@"Danger Ball":	[NSValue valueWithPointer:&dangerball_xscreensaver_function_table],
	@"Decay Screen":	[NSValue valueWithPointer:&decayscreen_xscreensaver_function_table],
	@"Deco":	[NSValue valueWithPointer:&deco_xscreensaver_function_table],
	@"Deep Stars":	[NSValue valueWithPointer:&deepstars_xscreensaver_function_table],
	@"Deluxe":	[NSValue valueWithPointer:&deluxe_xscreensaver_function_table],
	@"Demon":	[NSValue valueWithPointer:&demon_xscreensaver_function_table],
	@"Discoball":	[NSValue valueWithPointer:&discoball_xscreensaver_function_table],
	@"Discrete":	[NSValue valueWithPointer:&discrete_xscreensaver_function_table],
	@"Distort":	[NSValue valueWithPointer:&distort_xscreensaver_function_table],
	@"DNA Logo":	[NSValue valueWithPointer:&dnalogo_xscreensaver_function_table],
	@"Drift":	[NSValue valueWithPointer:&drift_xscreensaver_function_table],
	@"Dymaxion Map":	[NSValue valueWithPointer:&dymaxionmap_xscreensaver_function_table],
	@"Endgame":	[NSValue valueWithPointer:&endgame_xscreensaver_function_table],
	@"Energy Stream":	[NSValue valueWithPointer:&energystream_xscreensaver_function_table],
	@"Engine":	[NSValue valueWithPointer:&engine_xscreensaver_function_table],
	@"Epicycle":	[NSValue valueWithPointer:&epicycle_xscreensaver_function_table],
	@"Eruption":	[NSValue valueWithPointer:&eruption_xscreensaver_function_table],
	@"Esper":	[NSValue valueWithPointer:&esper_xscreensaver_function_table],
	@"Etruscan Venus":	[NSValue valueWithPointer:&etruscanvenus_xscreensaver_function_table],
	@"Euler 2D":	[NSValue valueWithPointer:&euler2d_xscreensaver_function_table],
	@"Fade Plot":	[NSValue valueWithPointer:&fadeplot_xscreensaver_function_table],
	@"Fiber Lamp":	[NSValue valueWithPointer:&fiberlamp_xscreensaver_function_table],
	@"Film Leader":	[NSValue valueWithPointer:&filmleader_xscreensaver_function_table],
	@"Fireworkx":	[NSValue valueWithPointer:&fireworkx_xscreensaver_function_table],
	@"Flame":	[NSValue valueWithPointer:&flame_xscreensaver_function_table],
	@"Flip Flop":	[NSValue valueWithPointer:&flipflop_xscreensaver_function_table],
	@"Flip Screen 3D":	[NSValue valueWithPointer:&flipscreen3d_xscreensaver_function_table],
	@"Flip Text":	[NSValue valueWithPointer:&fliptext_xscreensaver_function_table],
	@"Flow":	[NSValue valueWithPointer:&flow_xscreensaver_function_table],
	@"Fluid Balls":	[NSValue valueWithPointer:&fluidballs_xscreensaver_function_table],
	@"Flying Toasters":	[NSValue valueWithPointer:&flyingtoasters_xscreensaver_function_table],
	@"Font Glide":	[NSValue valueWithPointer:&fontglide_xscreensaver_function_table],
	@"Fuzzy Flakes":	[NSValue valueWithPointer:&fuzzyflakes_xscreensaver_function_table],
	@"Galaxy":	[NSValue valueWithPointer:&galaxy_xscreensaver_function_table],
	@"Gears":	[NSValue valueWithPointer:&gears_xscreensaver_function_table],
	@"Geodesic":	[NSValue valueWithPointer:&geodesic_xscreensaver_function_table],
	@"Geodesic Gears":	[NSValue valueWithPointer:&geodesicgears_xscreensaver_function_table],
	@"GFlux":	[NSValue valueWithPointer:&gflux_xscreensaver_function_table],
	@"Gibson":	[NSValue valueWithPointer:&gibson_xscreensaver_function_table],
	@"GL Blur":	[NSValue valueWithPointer:&glblur_xscreensaver_function_table],
	@"GL Cells":	[NSValue valueWithPointer:&glcells_xscreensaver_function_table],
	@"Gleidescope":	[NSValue valueWithPointer:&gleidescope_xscreensaver_function_table],
	@"GL Hanoi":	[NSValue valueWithPointer:&glhanoi_xscreensaver_function_table],
	@"GL Knots":	[NSValue valueWithPointer:&glknots_xscreensaver_function_table],
	@"GL Matrix":	[NSValue valueWithPointer:&glmatrix_xscreensaver_function_table],
	@"GL Planet":	[NSValue valueWithPointer:&glplanet_xscreensaver_function_table],
	@"GL School":	[NSValue valueWithPointer:&glschool_xscreensaver_function_table],
	@"GL Slideshow":	[NSValue valueWithPointer:&glslideshow_xscreensaver_function_table],
	@"GL Snake":	[NSValue valueWithPointer:&glsnake_xscreensaver_function_table],
	@"GL Text":	[NSValue valueWithPointer:&gltext_xscreensaver_function_table],
	@"Goop":	[NSValue valueWithPointer:&goop_xscreensaver_function_table],
	@"Grav":	[NSValue valueWithPointer:&grav_xscreensaver_function_table],
	@"Gravity Well":	[NSValue valueWithPointer:&gravitywell_xscreensaver_function_table],
	@"Greynetic":	[NSValue valueWithPointer:&greynetic_xscreensaver_function_table],
	@"Halftone":	[NSValue valueWithPointer:&halftone_xscreensaver_function_table],
	@"Halo":	[NSValue valueWithPointer:&halo_xscreensaver_function_table],
	@"Handsy":	[NSValue valueWithPointer:&handsy_xscreensaver_function_table],
	@"Headroom":	[NSValue valueWithPointer:&headroom_xscreensaver_function_table],
	@"Helix":	[NSValue valueWithPointer:&helix_xscreensaver_function_table],
	@"Hexadrop":	[NSValue valueWithPointer:&hexadrop_xscreensaver_function_table],
	@"Hex Strut":	[NSValue valueWithPointer:&hexstrut_xscreensaver_function_table],
	@"Hilbert":	[NSValue valueWithPointer:&hilbert_xscreensaver_function_table],
	@"Hopalong":	[NSValue valueWithPointer:&hopalong_xscreensaver_function_table],
	@"Hydrostat":	[NSValue valueWithPointer:&hydrostat_xscreensaver_function_table],
	@"Hypertorus":	[NSValue valueWithPointer:&hypertorus_xscreensaver_function_table],
	@"Hypnowheel":	[NSValue valueWithPointer:&hypnowheel_xscreensaver_function_table],
	@"IFS":	[NSValue valueWithPointer:&ifs_xscreensaver_function_table],
	@"IMS Map":	[NSValue valueWithPointer:&imsmap_xscreensaver_function_table],
	@"Interaggregate":	[NSValue valueWithPointer:&interaggregate_xscreensaver_function_table],
	@"Interference":	[NSValue valueWithPointer:&interference_xscreensaver_function_table],
	@"Intermomentary":	[NSValue valueWithPointer:&intermomentary_xscreensaver_function_table],
	@"Jiggly Puff":	[NSValue valueWithPointer:&jigglypuff_xscreensaver_function_table],
	@"Jigsaw":	[NSValue valueWithPointer:&jigsaw_xscreensaver_function_table],
	@"Juggler 3D":	[NSValue valueWithPointer:&juggler3d_xscreensaver_function_table],
	@"Julia":	[NSValue valueWithPointer:&julia_xscreensaver_function_table],
	@"Kaleidescope":	[NSValue valueWithPointer:&kaleidescope_xscreensaver_function_table],
	@"Kaleidocycle":	[NSValue valueWithPointer:&kaleidocycle_xscreensaver_function_table],
	@"Klein":	[NSValue valueWithPointer:&klein_xscreensaver_function_table],
	@"Kumppa":	[NSValue valueWithPointer:&kumppa_xscreensaver_function_table],
	@"Lament":	[NSValue valueWithPointer:&lament_xscreensaver_function_table],
	@"Lavalite":	[NSValue valueWithPointer:&lavalite_xscreensaver_function_table],
	@"Loop":	[NSValue valueWithPointer:&loop_xscreensaver_function_table],
	@"m6502":	[NSValue valueWithPointer:&m6502_xscreensaver_function_table],
	@"Maze":	[NSValue valueWithPointer:&maze_xscreensaver_function_table],
	@"Maze 3D":	[NSValue valueWithPointer:&maze3d_xscreensaver_function_table],
	@"Mem Scroller":	[NSValue valueWithPointer:&memscroller_xscreensaver_function_table],
	@"Menger":	[NSValue valueWithPointer:&menger_xscreensaver_function_table],
	@"Meta Balls":	[NSValue valueWithPointer:&metaballs_xscreensaver_function_table],
	@"Mirror Blob":	[NSValue valueWithPointer:&mirrorblob_xscreensaver_function_table],
	@"Möbius":	[NSValue valueWithPointer:&moebius_xscreensaver_function_table],
	@"Möbius Gears":	[NSValue valueWithPointer:&moebiusgears_xscreensaver_function_table],
	@"Moiré":	[NSValue valueWithPointer:&moire_xscreensaver_function_table],
	@"Moiré 2":	[NSValue valueWithPointer:&moire2_xscreensaver_function_table],
	@"Molecule":	[NSValue valueWithPointer:&molecule_xscreensaver_function_table],
	@"Morph 3D":	[NSValue valueWithPointer:&morph3d_xscreensaver_function_table],
	@"Mountain":	[NSValue valueWithPointer:&mountain_xscreensaver_function_table],
	@"Munch":	[NSValue valueWithPointer:&munch_xscreensaver_function_table],
	@"Nerve Rot":	[NSValue valueWithPointer:&nerverot_xscreensaver_function_table],
	@"Noof":	[NSValue valueWithPointer:&noof_xscreensaver_function_table],
	@"Nose Guy":	[NSValue valueWithPointer:&noseguy_xscreensaver_function_table],
	@"Pac-Man":	[NSValue valueWithPointer:&pacman_xscreensaver_function_table],
	@"Pedal":	[NSValue valueWithPointer:&pedal_xscreensaver_function_table],
	@"Peepers":	[NSValue valueWithPointer:&peepers_xscreensaver_function_table],
	@"Penetrate":	[NSValue valueWithPointer:&penetrate_xscreensaver_function_table],
	@"Penrose":	[NSValue valueWithPointer:&penrose_xscreensaver_function_table],
	@"Petri":	[NSValue valueWithPointer:&petri_xscreensaver_function_table],
	@"Phosphor":	[NSValue valueWithPointer:&phosphor_xscreensaver_function_table],
	@"Photo Pile":	[NSValue valueWithPointer:&photopile_xscreensaver_function_table],
	@"Piecewise":	[NSValue valueWithPointer:&piecewise_xscreensaver_function_table],
	@"Pinion":	[NSValue valueWithPointer:&pinion_xscreensaver_function_table],
	@"Pipes":	[NSValue valueWithPointer:&pipes_xscreensaver_function_table],
	@"Polyhedra":	[NSValue valueWithPointer:&polyhedra_xscreensaver_function_table],
	@"Polyominoes":	[NSValue valueWithPointer:&polyominoes_xscreensaver_function_table],
	@"Polytopes":	[NSValue valueWithPointer:&polytopes_xscreensaver_function_table],
	@"Pong":	[NSValue valueWithPointer:&pong_xscreensaver_function_table],
	@"Pop Squares":	[NSValue valueWithPointer:&popsquares_xscreensaver_function_table],
	@"Projective Plane":	[NSValue valueWithPointer:&projectiveplane_xscreensaver_function_table],
	@"Providence":	[NSValue valueWithPointer:&providence_xscreensaver_function_table],
	@"Pulsar":	[NSValue valueWithPointer:&pulsar_xscreensaver_function_table],
	@"Pyro":	[NSValue valueWithPointer:&pyro_xscreensaver_function_table],
	@"Qix":	[NSValue valueWithPointer:&qix_xscreensaver_function_table],
	@"Quasi-Crystal":	[NSValue valueWithPointer:&quasicrystal_xscreensaver_function_table],
	@"Queens":	[NSValue valueWithPointer:&queens_xscreensaver_function_table],
	@"Raver Hoop":	[NSValue valueWithPointer:&raverhoop_xscreensaver_function_table],
	@"Razzle Dazzle":	[NSValue valueWithPointer:&razzledazzle_xscreensaver_function_table],
	@"RD-Bomb":	[NSValue valueWithPointer:&rdbomb_xscreensaver_function_table],
	@"Ripples":	[NSValue valueWithPointer:&ripples_xscreensaver_function_table],
	@"Rocks":	[NSValue valueWithPointer:&rocks_xscreensaver_function_table],
	@"Roman Boy":	[NSValue valueWithPointer:&romanboy_xscreensaver_function_table],
	@"Rorschach":	[NSValue valueWithPointer:&rorschach_xscreensaver_function_table],
	@"Rot Zoomer":	[NSValue valueWithPointer:&rotzoomer_xscreensaver_function_table],
	@"Rubik":	[NSValue valueWithPointer:&rubik_xscreensaver_function_table],
	@"Rubik Blocks":	[NSValue valueWithPointer:&rubikblocks_xscreensaver_function_table],
	@"SBalls":	[NSValue valueWithPointer:&sballs_xscreensaver_function_table],
	@"Scooter":	[NSValue valueWithPointer:&scooter_xscreensaver_function_table],
	@"Shade Bobs":	[NSValue valueWithPointer:&shadebobs_xscreensaver_function_table],
	@"Sierpinski":	[NSValue valueWithPointer:&sierpinski_xscreensaver_function_table],
	@"Sierpinski 3D":	[NSValue valueWithPointer:&sierpinski3d_xscreensaver_function_table],
	@"Sky Tentacles":	[NSValue valueWithPointer:&skytentacles_xscreensaver_function_table],
	@"Slide Screen":	[NSValue valueWithPointer:&slidescreen_xscreensaver_function_table],
	@"Slip":	[NSValue valueWithPointer:&slip_xscreensaver_function_table],
	@"Sonar":	[NSValue valueWithPointer:&sonar_xscreensaver_function_table],
	@"Speed Mine":	[NSValue valueWithPointer:&speedmine_xscreensaver_function_table],
	@"Sphere Eversion":	[NSValue valueWithPointer:&sphereeversion_xscreensaver_function_table],
	@"Spheremonics":	[NSValue valueWithPointer:&spheremonics_xscreensaver_function_table],
	@"Split-Flap":	[NSValue valueWithPointer:&splitflap_xscreensaver_function_table],
	@"Splodesic":	[NSValue valueWithPointer:&splodesic_xscreensaver_function_table],
	@"Spotlight":	[NSValue valueWithPointer:&spotlight_xscreensaver_function_table],
	@"Sproingies":	[NSValue valueWithPointer:&sproingies_xscreensaver_function_table],
	@"Squiral":	[NSValue valueWithPointer:&squiral_xscreensaver_function_table],
	@"Stairs":	[NSValue valueWithPointer:&stairs_xscreensaver_function_table],
	@"Starfish":	[NSValue valueWithPointer:&starfish_xscreensaver_function_table],
	@"Star Wars":	[NSValue valueWithPointer:&starwars_xscreensaver_function_table],
	@"Stoner View":	[NSValue valueWithPointer:&stonerview_xscreensaver_function_table],
	@"Strange":	[NSValue valueWithPointer:&strange_xscreensaver_function_table],
	@"Substrate":	[NSValue valueWithPointer:&substrate_xscreensaver_function_table],
	@"Superquadrics":	[NSValue valueWithPointer:&superquadrics_xscreensaver_function_table],
	@"Surfaces":	[NSValue valueWithPointer:&surfaces_xscreensaver_function_table],
	@"Swirl":	[NSValue valueWithPointer:&swirl_xscreensaver_function_table],
	@"Tangram":	[NSValue valueWithPointer:&tangram_xscreensaver_function_table],
	@"Tessellimage":	[NSValue valueWithPointer:&tessellimage_xscreensaver_function_table],
	@"Thornbird":	[NSValue valueWithPointer:&thornbird_xscreensaver_function_table],
	@"Time Tunnel":	[NSValue valueWithPointer:&timetunnel_xscreensaver_function_table],
	@"Top Block":	[NSValue valueWithPointer:&topblock_xscreensaver_function_table],
	@"Triangle":	[NSValue valueWithPointer:&triangle_xscreensaver_function_table],
	@"Tron Bit":	[NSValue valueWithPointer:&tronbit_xscreensaver_function_table],
	@"Truchet":	[NSValue valueWithPointer:&truchet_xscreensaver_function_table],
	@"Twang":	[NSValue valueWithPointer:&twang_xscreensaver_function_table],
	@"Unicrud":	[NSValue valueWithPointer:&unicrud_xscreensaver_function_table],
	@"Unknown Pleasures":	[NSValue valueWithPointer:&unknownpleasures_xscreensaver_function_table],
	@"Vermiculate":	[NSValue valueWithPointer:&vermiculate_xscreensaver_function_table],
	@"VFeedback":	[NSValue valueWithPointer:&vfeedback_xscreensaver_function_table],
	@"Vigilance":	[NSValue valueWithPointer:&vigilance_xscreensaver_function_table],
	@"Voronoi":	[NSValue valueWithPointer:&voronoi_xscreensaver_function_table],
	@"Wander":	[NSValue valueWithPointer:&wander_xscreensaver_function_table],
	@"Whirlwind Warp":	[NSValue valueWithPointer:&whirlwindwarp_xscreensaver_function_table],
	@"Windup Robot":	[NSValue valueWithPointer:&winduprobot_xscreensaver_function_table],
	@"Wormhole":	[NSValue valueWithPointer:&wormhole_xscreensaver_function_table],
	@"XAnalogTV":	[NSValue valueWithPointer:&xanalogtv_xscreensaver_function_table],
	@"XFlame":	[NSValue valueWithPointer:&xflame_xscreensaver_function_table],
	@"XJack":	[NSValue valueWithPointer:&xjack_xscreensaver_function_table],
	@"XLyap":	[NSValue valueWithPointer:&xlyap_xscreensaver_function_table],
	@"XMatrix":	[NSValue valueWithPointer:&xmatrix_xscreensaver_function_table],
	@"XRaySwarm":	[NSValue valueWithPointer:&xrayswarm_xscreensaver_function_table],
	@"XSpirograph":	[NSValue valueWithPointer:&xspirograph_xscreensaver_function_table],
	@"Zoom":	[NSValue valueWithPointer:&zoom_xscreensaver_function_table],
#endif
	};
}

