.TH XScreenSaver 1 "5-May-2004"
.SH NAME
endgame \- re-play classic chess games
.SH SYNOPSIS
.B endgame
[\-\-display \fIhost:display.screen\fP]
[\-\-window]
[\-\-root]
[\-\-window\-id \fInumber\fP]
[\-\-install]
[\-\-visual \fIvisual\fP]
[\-\-delay \fImicroseconds\fP]
[\-\-wireframe]
[\-\-fps]
.SH DESCRIPTION
endgame replays a brilliant chess ending
.SH OPTIONS
.I endgame
accepts the following options:
.TP 8
.B \-\-window
Draw on a newly-created window.  This is the default.
.TP 8
.B \-\-root
Draw on the root window.
.TP 8
.B \-\-window\-id \fInumber\fP
Draw on the specified window.
.TP 8
.B \-\-install
Install a private colormap for the window.
.TP 8
.B \-\-shadows
Project pieces against the board with dark blend.
.TP 8
.B \-\-reflections
Reflect pieces in light board squares.
.TP 8
.B \-\-classic
Use the original low-polygon piece models.
.TP 8
.B \-\-labels
Display information about the current game and move.
.TP 8
.B \-\-visual \fIvisual\fP\fP
Specify which visual to use.  Legal values are the name of a visual class,
or the id number (decimal or hex) of a specific visual.
.TP 8
.B \-\-wireframe
Render in wireframe instead of solid.
.B \-\-fps
Display the current frame rate, CPU load, and polygon count.
.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY
to get the default host and display number.
.TP 8
.B XENVIRONMENT
to get the name of a resource file that overrides the global resources
stored in the RESOURCE_MANAGER property.
.TP 8
.B XSCREENSAVER_WINDOW
The window ID to use with \fI\-\-root\fP.
.SH SEE ALSO
.BR X (1),
.BR xscreensaver (1)
.BR xscreensaver\-settings (1),
.BR xscreensaver\-getimage (MANSUFFIX)
.SH COPYRIGHT
Copyright \(co 2002 by Blair Tennessy.  Permission to use, copy, modify,
distribute, and sell this software and its documentation for any purpose is
hereby granted without fee, provided that the above copyright notice appear
in all copies and that both that copyright notice and this permission notice
appear in supporting documentation.  No representations are made about the
suitability of this software for any purpose.  It is provided "as is" without
express or implied warranty.
.SH AUTHOR
Blair Tennessy <tennessb@unbc.ca>, 20-April-2002.
 
